### ISSUE TITLE
Deverlopment local Kubernetes root permissions

### ISSUE THREAD

**Issue by wcarlsen** [dfds/k8s-janitor#23]
When developing for the janitor we normally spin up a local Kubernetes like Minikube or Kind and then the janitor pick up the kube-config file on the local filesystem and operate towards this local instance of Kubernetes with root access. This is all good and well, but our janitor doesn't have root access and therefore we introduce a gap in permissions between local development and production. Let's make sure that we emulate production as much as possible.

**Comment by wcarlsen** [comment]
This might help if we just apply this on our local Kubernetes https://github.com/dfds/k8s-janitor/blob/master/k8s/permissions.yml

**Comment by ZaradarDFDS** [comment]
Why is this a bug? Why do we associate the access of our dev to k8s with the general access required by the janitor? The reason why we need this access is for debugging purposes, as such our process will run using the account created by the manifest you linked and thus it has nothing to do with the problem you specified.

**Comment by wcarlsen** [comment]
Closing this because clearly the point was miss understood and we don't care about a miss alignment in development flow and production that can and has caused outages.
